//! Numeric verification of the Metal ArtCNN luma upscaler against
//! onnxruntime reference outputs generated by
//! `assets/artcnn/export_artcnn.py --test-vector`.

#![cfg(any(target_os = "macos", target_os = "ios"))]

use std::ffi::c_void;
use std::ptr::NonNull;

use objc2::rc::Retained;
use objc2::runtime::ProtocolObject;
use objc2_metal::{
    MTLBlitCommandEncoder, MTLBuffer, MTLCommandBuffer, MTLCommandEncoder, MTLCommandQueue,
    MTLCreateSystemDefaultDevice, MTLDevice, MTLGPUFamily, MTLOrigin, MTLPixelFormat, MTLRegion,
    MTLResourceOptions, MTLSize, MTLTexture, MTLTextureDescriptor, MTLTextureUsage,
};

use erika::renderer::metal::upscaler::{LumaUpscaler, UpscalerBackend};
use erika::renderer::metal::LumaUpscalerMode;

const WIDTH: usize = 128;
const HEIGHT: usize = 72;

fn load_f32(bytes: &[u8]) -> Vec<f32> {
    bytes
        .chunks_exact(4)
        .map(|chunk| f32::from_le_bytes(chunk.try_into().expect("4 bytes")))
        .collect()
}

fn run_upscaler(mode: LumaUpscalerMode, backend: UpscalerBackend, input: &[f32]) -> Vec<f32> {
    run_upscaler_sized(mode, backend, input, WIDTH, HEIGHT)
}

fn system_supports_simdgroup_matrix() -> bool {
    MTLCreateSystemDefaultDevice()
        .expect("Metal device")
        .supportsFamily(MTLGPUFamily::Apple7)
}

fn run_upscaler_sized(
    mode: LumaUpscalerMode,
    backend: UpscalerBackend,
    input: &[f32],
    width: usize,
    height: usize,
) -> Vec<f32> {
    let device = MTLCreateSystemDefaultDevice().expect("Metal device");
    let queue = device.newCommandQueue().expect("command queue");

    // Input luma as R8Unorm, exactly like an NV12 plane. The test vector is
    // already quantized to the 8-bit grid, so the upload is lossless.
    let descriptor = unsafe {
        let descriptor =
            MTLTextureDescriptor::texture2DDescriptorWithPixelFormat_width_height_mipmapped(
                MTLPixelFormat::R8Unorm,
                width,
                height,
                false,
            );
        descriptor.setUsage(MTLTextureUsage::ShaderRead);
        descriptor
    };
    let luma = device
        .newTextureWithDescriptor(&descriptor)
        .expect("luma texture");
    let bytes: Vec<u8> = input
        .iter()
        .map(|value| (value * 255.0).round().clamp(0.0, 255.0) as u8)
        .collect();
    unsafe {
        luma.replaceRegion_mipmapLevel_withBytes_bytesPerRow(
            MTLRegion {
                origin: MTLOrigin { x: 0, y: 0, z: 0 },
                size: MTLSize {
                    width,
                    height,
                    depth: 1,
                },
            },
            0,
            NonNull::new(bytes.as_ptr().cast::<c_void>().cast_mut()).expect("bytes non-null"),
            width,
        );
    }

    let mut upscaler = LumaUpscaler::default();
    upscaler.set_mode(mode);
    upscaler.set_backend(backend);
    upscaler
        .prepare_blocking(&device)
        .expect("prepare upscaler");
    let command_buffer = queue.commandBuffer().expect("command buffer");
    // R16Float output isolates kernel error from output quantization.
    let output: Retained<ProtocolObject<dyn MTLTexture>> = upscaler
        .encode(&device, &command_buffer, &luma, MTLPixelFormat::R16Float)
        .expect("encode upscaler")
        .expect("upscaler enabled");

    let out_width = width * 2;
    let out_height = height * 2;
    let row_bytes = out_width * 2;
    let readback = device
        .newBufferWithLength_options(
            row_bytes * out_height,
            MTLResourceOptions::StorageModeShared,
        )
        .expect("readback buffer");
    let blit = command_buffer.blitCommandEncoder().expect("blit encoder");
    unsafe {
        blit.copyFromTexture_sourceSlice_sourceLevel_sourceOrigin_sourceSize_toBuffer_destinationOffset_destinationBytesPerRow_destinationBytesPerImage(
            &output,
            0,
            0,
            MTLOrigin { x: 0, y: 0, z: 0 },
            MTLSize {
                width: out_width,
                height: out_height,
                depth: 1,
            },
            &readback,
            0,
            row_bytes,
            row_bytes * out_height,
        );
    }
    blit.endEncoding();
    command_buffer.commit();
    command_buffer.waitUntilCompleted();

    let contents = readback.contents().as_ptr().cast::<u16>();
    let mut result = Vec::with_capacity(out_width * out_height);
    for index in 0..out_width * out_height {
        let bits = unsafe { *contents.add(index) };
        result.push(half_to_f32(bits));
    }
    result
}

fn half_to_f32(bits: u16) -> f32 {
    let sign = u32::from(bits >> 15) << 31;
    let exponent = u32::from((bits >> 10) & 0x1F);
    let mantissa = u32::from(bits & 0x3FF);
    let value = match (exponent, mantissa) {
        (0, 0) => sign,
        (0, _) => {
            // subnormal half
            let shift = mantissa.leading_zeros() - 21;
            let exponent = 127 - 15 - shift;
            let mantissa = (mantissa << (shift + 1)) & 0x3FF;
            sign | (exponent << 23) | (mantissa << 13)
        }
        (0x1F, 0) => sign | 0x7F80_0000,
        (0x1F, _) => sign | 0x7FC0_0000,
        _ => sign | ((exponent + 127 - 15) << 23) | (mantissa << 13),
    };
    f32::from_bits(value)
}

struct ErrorStats {
    mae: f64,
    max: f64,
    psnr: f64,
}

fn compare(actual: &[f32], expected: &[f32]) -> ErrorStats {
    assert_eq!(actual.len(), expected.len());
    let mut sum_abs = 0.0f64;
    let mut sum_sq = 0.0f64;
    let mut max = 0.0f64;
    for (a, e) in actual.iter().zip(expected) {
        let diff = (f64::from(*a) - f64::from(*e)).abs();
        sum_abs += diff;
        sum_sq += diff * diff;
        max = max.max(diff);
    }
    let count = actual.len() as f64;
    let mse = sum_sq / count;
    ErrorStats {
        mae: sum_abs / count,
        max,
        psnr: -10.0 * mse.max(1e-12).log10(),
    }
}

fn check_against_reference(
    mode: LumaUpscalerMode,
    backend: UpscalerBackend,
    input: &[u8],
    expected: &[u8],
) {
    if backend == UpscalerBackend::SimdgroupMatrix && !system_supports_simdgroup_matrix() {
        eprintln!("skipping {mode:?}/SimdgroupMatrix: GPU family lacks simdgroup_matrix support");
        return;
    }
    let input = load_f32(input);
    let expected = load_f32(expected);
    let actual = run_upscaler(mode, backend, &input);
    let stats = compare(&actual, &expected);
    eprintln!(
        "{mode:?}/{backend:?}: mae={:.6} max={:.6} psnr={:.2} dB",
        stats.mae, stats.max, stats.psnr
    );
    // fp16 accumulation against an fp32 onnxruntime reference: demand well
    // below one 8-bit LSB (1/255 ~ 3.9e-3) on average.
    assert!(stats.mae < 1.5e-3, "MAE too high: {}", stats.mae);
    assert!(stats.max < 2.0e-2, "max error too high: {}", stats.max);
}

#[test]
fn artcnn_c4f16_scalar_matches_onnx_reference() {
    check_against_reference(
        LumaUpscalerMode::ArtCnnC4F16,
        UpscalerBackend::Scalar,
        include_bytes!("data/artcnn/c4f16/input_128x72.f32"),
        include_bytes!("data/artcnn/c4f16/output_256x144.f32"),
    );
}

#[test]
fn artcnn_c4f32_scalar_matches_onnx_reference() {
    check_against_reference(
        LumaUpscalerMode::ArtCnnC4F32,
        UpscalerBackend::Scalar,
        include_bytes!("data/artcnn/c4f32/input_128x72.f32"),
        include_bytes!("data/artcnn/c4f32/output_256x144.f32"),
    );
}

#[test]
fn artcnn_c4f16_matmul_matches_onnx_reference() {
    check_against_reference(
        LumaUpscalerMode::ArtCnnC4F16,
        UpscalerBackend::SimdgroupMatrix,
        include_bytes!("data/artcnn/c4f16/input_128x72.f32"),
        include_bytes!("data/artcnn/c4f16/output_256x144.f32"),
    );
}

#[test]
fn artcnn_c4f32_matmul_matches_onnx_reference() {
    check_against_reference(
        LumaUpscalerMode::ArtCnnC4F32,
        UpscalerBackend::SimdgroupMatrix,
        include_bytes!("data/artcnn/c4f32/input_128x72.f32"),
        include_bytes!("data/artcnn/c4f32/output_256x144.f32"),
    );
}

/// GPU micro-benchmark at 1080p. Run with:
/// `cargo test --release -p erika --test artcnn_upscaler -- --ignored --nocapture bench`
#[test]
#[ignore]
fn bench_1080p_gpu_time() {
    for backend in [UpscalerBackend::Scalar, UpscalerBackend::SimdgroupMatrix] {
        for mode in [LumaUpscalerMode::ArtCnnC4F16, LumaUpscalerMode::ArtCnnC4F32] {
            bench_mode(mode, backend, 1920, 1080, 30);
            bench_mode(mode, backend, 960, 540, 30);
        }
    }
}

fn bench_mode(
    mode: LumaUpscalerMode,
    backend: UpscalerBackend,
    width: usize,
    height: usize,
    frames: usize,
) {
    let device = MTLCreateSystemDefaultDevice().expect("Metal device");
    let queue = device.newCommandQueue().expect("command queue");
    let descriptor = unsafe {
        let descriptor =
            MTLTextureDescriptor::texture2DDescriptorWithPixelFormat_width_height_mipmapped(
                MTLPixelFormat::R8Unorm,
                width,
                height,
                false,
            );
        descriptor.setUsage(MTLTextureUsage::ShaderRead);
        descriptor
    };
    let luma = device
        .newTextureWithDescriptor(&descriptor)
        .expect("luma texture");
    let bytes: Vec<u8> = (0..width * height).map(|i| (i % 251) as u8).collect();
    unsafe {
        luma.replaceRegion_mipmapLevel_withBytes_bytesPerRow(
            MTLRegion {
                origin: MTLOrigin { x: 0, y: 0, z: 0 },
                size: MTLSize {
                    width,
                    height,
                    depth: 1,
                },
            },
            0,
            NonNull::new(bytes.as_ptr().cast::<c_void>().cast_mut()).expect("non-null"),
            width,
        );
    }

    let mut upscaler = LumaUpscaler::default();
    upscaler.set_mode(mode);
    upscaler.set_backend(backend);
    upscaler
        .prepare_blocking(&device)
        .expect("prepare upscaler");
    let mut gpu_seconds = Vec::new();
    for frame in 0..frames {
        let command_buffer = queue.commandBuffer().expect("command buffer");
        upscaler
            .encode(&device, &command_buffer, &luma, MTLPixelFormat::R8Unorm)
            .expect("encode")
            .expect("enabled");
        command_buffer.commit();
        command_buffer.waitUntilCompleted();
        if frame >= 5 {
            gpu_seconds.push(command_buffer.GPUEndTime() - command_buffer.GPUStartTime());
        }
    }
    let avg = gpu_seconds.iter().sum::<f64>() / gpu_seconds.len() as f64;
    let min = gpu_seconds.iter().cloned().fold(f64::MAX, f64::min);
    eprintln!(
        "{mode:?}/{backend:?} {width}x{height}: gpu avg={:.3} ms min={:.3} ms",
        avg * 1e3,
        min * 1e3
    );
}

/// File-driven harness for offline quality comparisons. Reads a raw f32 luma
/// plane, upscales it with the requested variant, writes raw f32 output.
/// Driven by env vars: ERIKA_SR_IN, ERIKA_SR_W, ERIKA_SR_H, ERIKA_SR_OUT,
/// ERIKA_SR_MODE (c4f16|c4f32).
#[test]
#[ignore]
fn dump_upscaled_from_env() {
    let input_path = std::env::var("ERIKA_SR_IN").expect("ERIKA_SR_IN");
    let output_path = std::env::var("ERIKA_SR_OUT").expect("ERIKA_SR_OUT");
    let width: usize = std::env::var("ERIKA_SR_W").expect("W").parse().expect("W");
    let height: usize = std::env::var("ERIKA_SR_H").expect("H").parse().expect("H");
    let mode = match std::env::var("ERIKA_SR_MODE").as_deref() {
        Ok("c4f32") => LumaUpscalerMode::ArtCnnC4F32,
        _ => LumaUpscalerMode::ArtCnnC4F16,
    };
    let backend = match std::env::var("ERIKA_SR_TEST_BACKEND").as_deref() {
        Ok("scalar") => UpscalerBackend::Scalar,
        Ok("matmul") => UpscalerBackend::SimdgroupMatrix,
        _ => UpscalerBackend::Auto,
    };
    let input = load_f32(&std::fs::read(&input_path).expect("read input"));
    assert_eq!(input.len(), width * height, "input size mismatch");
    let output = run_upscaler_sized(mode, backend, &input, width, height);
    let bytes: Vec<u8> = output.iter().flat_map(|v| v.to_le_bytes()).collect();
    std::fs::write(&output_path, bytes).expect("write output");
    eprintln!("wrote {}x{} -> {}", width * 2, height * 2, output_path);
}
